### PR TITLE
python bytecode post

### PR DESCRIPTION
**Pull request by renewang**
以 pycon 2016 Playing with Python Bytecode 演講寫成的文章。請 review 。謝謝！

### CODE REVIEW

**Comment by kdchang** [comment]
cool. please @ArvinH @Po-Jen @aszx87410 take a look. thank you :)

**Review by ArvinH — APPROVED** [review]
Nice article and sorry for the late reply 😄

**Comment by ArvinH** [comment]
@aszx87410 @kdchang @Po-Jen One more review then we good to go 🍔

**Comment by aszx87410** [comment]
@ArvinH Yep, It's definitely a good article, I think we can merge this.

**Comment by renewang** [comment]
Thanks! :)

**Comment by kdchang** [comment]
hi @renewang, 

Could give me your email that I can add you into our editor slack channel. :)
Please send it to me, thank you !

kdchang.cc [at] gmail.com

**Pull request merged**
