### PR TITLE
Submit: A Crypto Management UX Case Study

### PR DESCRIPTION
**Pull request by ledtorch**
I’m working for a blockchain company and I wrote this report for our Beta version and sharing my works.

Thanks for any feedback or suggestion.

### CODE REVIEW

**Comment by kdchang** [comment]
Thank you @ledtorch for your submission. :)

hi @ArvinH @Po-Jen @aszx87410, please help to review this PR. Thank you :)

**Comment by kdchang** [comment]
Hi @ledtorch,

Sorry for the late reply. Our tech blog focus on Traditional Chinese tech article sharing now, so would you mind translating your article to Traditional Chinese version ? thank you :)

BTW, we found your post demo video and some text format are broken :
img
img

cc @ArvinH @aszx87410 @Po-Jen

**Comment by ledtorch** [comment]
Thanks for your reply.

**Comment by kdchang** [comment]
No problem, thank you @ledtorch :)

**Pull request closed without merging**
