### PR TITLE
add binary-data-manipulations-in-javascript

### PR DESCRIPTION
**Pull request by weihanglo**
Hi, this is my first submission to TechBridge blog. I am not quite sure whether this post is appropriate. Please let me know if there is any mistakes. Thanks!

By the way, would you prefer to discuss in English, or Chinese is acceptable?

### CODE REVIEW

**Comment by kdchang** [comment]
Hi @weihanglo,

Cool. Thanks for your contribution, this post is great !

Both English and Chinese are fine for us, so it’s up to you :) 

BTW, commit message should be English.

@ArvinH @aszx87410  Please take a look, thank you~

**Comment by aszx87410** [comment]
十分驚艷的一篇文章

因為目前 JavaScript 的相關文章都是著重在前端方面，例如說一些跟瀏覽器相關的操作或者是視覺化，很少看到這樣專門講解 binary 操作的文章。

寫得很詳細，但這方面我也不是太熟，所以有錯的話我應該也抓不太出來XD

總之整篇文章真的很棒，如果以後碰到相關問題要處理，我一定再跑回來看這篇文章複習一遍。

**Comment by weihanglo** [comment]
Thanks for reviewing my commit, I think I may still use English in any public Github thread.
Off topic. If I did not misunderstand, the only way to become a curator is to submit at least 4 articles?

**Review by ArvinH — APPROVED** [review]
I don't know much about Typed Array but this is a great article with detail introduction 👍 
Maybe you can write another article about how to manipulate Typed Array with WASM.

And yes we do have rules for joining us.
In issues: https://github.com/TechBridgeWeekly/blog-starter-kit/issues/2

**Comment by ArvinH** [comment]
@weihanglo  Your article will be sent to our subscribers in next newsletters 😄

**Comment by weihanglo** [comment]
Very glad to see my commit to be approved. And I love the WASM idea! I will try to compose some post about WASM if possible.

**Comment by kdchang** [comment]
Hi @weihanglo,

Congratulation ! Please send me your email (kdchang.cc [at] gmail.com), I will invite you to our slack. Thank you ;)

**Pull request merged**
